# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

stages:
- stage: build
  jobs:
    - job: build
      pool:
        vmImage: 'windows-latest'

      steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

- stage: Deploy
  jobs:
    - job: Deploy
      pool:
        vmImage: 'windows-latest'

      steps:
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Avaliação Gratuita(403cea73-066c-45ec-b80f-dfb208b5efcc)'
          appType: 'webApp'
          WebAppName: 'AshayCore'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
